channels:
  - conda-forge
variables:
  - CMAKE_ARGS: -DLLAMA_CUBLAS=on
dependencies:
  - python=3.10.14
  - pip:
    - llama-cpp-python
    - torch==1.10.0 --index-url https://download.pytorch.org/whl/nightly/cu121
    - torchvision==0.11.1 --index-url https://download.pytorch.org/whl/nightly/cu121
    - torchaudio==0.10.0 --index-url https://download.pytorch.org/whl/nightly/cu121
    - openpyxl
    - langchain-community
    - gradio
    - accelerate
    - bitsandbytes
    - kaleido
    - python-multipart
    - langchain
    - chromadb
    - langchainhub
    - beautifulsoup4
    - instructor-embedding
    - sentence-transformers
    - docx2txt
    - gpt4all
    - unstructured[pdf]
name: mlflow-env
