channels:
- conda-forge
python: 3.10.14
build_dependencies:
- pip==24.0
- setuptools==69.5.1
- wheel==0.43.0
dependencies:
- python=3.10.14
- -r requirements.txt
name: mlflow-env
# CMAKE_ARGS="-DLLAMA_CUBLAS=on" conda env create -f conda.yaml